/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package info.cukes.feature.options;

import java.awt.Color;
import javax.swing.JColorChooser;
import org.openide.util.NbPreferences;

final class CucumberFeatureOptionsPanel extends javax.swing.JPanel {

    private final CucumberFeatureOptionsOptionsPanelController controller;

    CucumberFeatureOptionsPanel(CucumberFeatureOptionsOptionsPanelController controller) {
        this.controller = controller;
        initComponents();
        // TODO listen to changes in form fields and call controller.changed()
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseStringsColorButton = new javax.swing.JButton();
        stringsColorTextField = new javax.swing.JFormattedTextField();
        stringsLabel = new javax.swing.JLabel();
        stringsColorPreviewPanel = new javax.swing.JPanel();
        examplesColorPreviewPanel = new javax.swing.JPanel();
        backgroundColorPreviewPanel = new javax.swing.JPanel();
        scenarioColorPreviewPanel = new javax.swing.JPanel();
        featureColorPreviewPanel = new javax.swing.JPanel();
        featureLabel = new javax.swing.JLabel();
        scenarioLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        examplesLabel = new javax.swing.JLabel();
        examplesColorTextField = new javax.swing.JFormattedTextField();
        backgroundColorTextField = new javax.swing.JFormattedTextField();
        scenarioColorTextField = new javax.swing.JFormattedTextField();
        chooseFeatureColorButton = new javax.swing.JButton();
        chooseScenarioColorButton = new javax.swing.JButton();
        chooseBackgroundColorButton = new javax.swing.JButton();
        chooseExamplesColorButton = new javax.swing.JButton();
        pyStringsColorPreviewPanel = new javax.swing.JPanel();
        pyStringsLabel = new javax.swing.JLabel();
        pyStringsColorTextField = new javax.swing.JFormattedTextField();
        choosePyStringsColorButton = new javax.swing.JButton();
        chooseVariablesColorButton = new javax.swing.JButton();
        variablesColorTextField = new javax.swing.JFormattedTextField();
        variablesLabel = new javax.swing.JLabel();
        variablesColorPreviewPanel = new javax.swing.JPanel();
        numbersLabel = new javax.swing.JLabel();
        chooseNumbersColorButton = new javax.swing.JButton();
        numbersColorTextField = new javax.swing.JFormattedTextField();
        numbersColorPreviewPanel = new javax.swing.JPanel();
        featureColorTextField = new javax.swing.JFormattedTextField();
        chooseCommentsColorButton = new javax.swing.JButton();
        commentsColorTextField = new javax.swing.JFormattedTextField();
        commentsLabel = new javax.swing.JLabel();
        commentsColorPreviewPanel = new javax.swing.JPanel();
        chooseStepsColorButton = new javax.swing.JButton();
        stepsColorTextField = new javax.swing.JFormattedTextField();
        stepsLabel = new javax.swing.JLabel();
        stepsColorPreviewPanel = new javax.swing.JPanel();

        org.openide.awt.Mnemonics.setLocalizedText(chooseStringsColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseStringsColorButton.text")); // NOI18N
        chooseStringsColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseStringsColorButtonActionPerformed(evt);
            }
        });

        stringsColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.stringsColorTextField.text")); // NOI18N
        stringsColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        stringsColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(stringsLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.stringsLabel.text")); // NOI18N

        stringsColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stringsColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        stringsColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout stringsColorPreviewPanelLayout = new javax.swing.GroupLayout(stringsColorPreviewPanel);
        stringsColorPreviewPanel.setLayout(stringsColorPreviewPanelLayout);
        stringsColorPreviewPanelLayout.setHorizontalGroup(
            stringsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        stringsColorPreviewPanelLayout.setVerticalGroup(
            stringsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        examplesColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        examplesColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        examplesColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout examplesColorPreviewPanelLayout = new javax.swing.GroupLayout(examplesColorPreviewPanel);
        examplesColorPreviewPanel.setLayout(examplesColorPreviewPanelLayout);
        examplesColorPreviewPanelLayout.setHorizontalGroup(
            examplesColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        examplesColorPreviewPanelLayout.setVerticalGroup(
            examplesColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        backgroundColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backgroundColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        backgroundColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        backgroundColorPreviewPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout backgroundColorPreviewPanelLayout = new javax.swing.GroupLayout(backgroundColorPreviewPanel);
        backgroundColorPreviewPanel.setLayout(backgroundColorPreviewPanelLayout);
        backgroundColorPreviewPanelLayout.setHorizontalGroup(
            backgroundColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        backgroundColorPreviewPanelLayout.setVerticalGroup(
            backgroundColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        scenarioColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scenarioColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        scenarioColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        scenarioColorPreviewPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout scenarioColorPreviewPanelLayout = new javax.swing.GroupLayout(scenarioColorPreviewPanel);
        scenarioColorPreviewPanel.setLayout(scenarioColorPreviewPanelLayout);
        scenarioColorPreviewPanelLayout.setHorizontalGroup(
            scenarioColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        scenarioColorPreviewPanelLayout.setVerticalGroup(
            scenarioColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        featureColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        featureColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        featureColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));
        featureColorPreviewPanel.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout featureColorPreviewPanelLayout = new javax.swing.GroupLayout(featureColorPreviewPanel);
        featureColorPreviewPanel.setLayout(featureColorPreviewPanelLayout);
        featureColorPreviewPanelLayout.setHorizontalGroup(
            featureColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        featureColorPreviewPanelLayout.setVerticalGroup(
            featureColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        featureLabel.setLabelFor(featureColorTextField);
        org.openide.awt.Mnemonics.setLocalizedText(featureLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.featureLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(scenarioLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.scenarioLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(backgroundLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.backgroundLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(examplesLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.examplesLabel.text")); // NOI18N

        examplesColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.examplesColorTextField.text")); // NOI18N
        examplesColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        examplesColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        backgroundColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.backgroundColorTextField.text")); // NOI18N
        backgroundColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        backgroundColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        scenarioColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.scenarioColorTextField.text")); // NOI18N
        scenarioColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        scenarioColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(chooseFeatureColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseFeatureColorButton.text")); // NOI18N
        chooseFeatureColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseFeatureColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chooseScenarioColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseScenarioColorButton.text")); // NOI18N
        chooseScenarioColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseScenarioColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chooseBackgroundColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseBackgroundColorButton.text")); // NOI18N
        chooseBackgroundColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseBackgroundColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chooseExamplesColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseExamplesColorButton.text")); // NOI18N
        chooseExamplesColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseExamplesColorButtonActionPerformed(evt);
            }
        });

        pyStringsColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pyStringsColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        pyStringsColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout pyStringsColorPreviewPanelLayout = new javax.swing.GroupLayout(pyStringsColorPreviewPanel);
        pyStringsColorPreviewPanel.setLayout(pyStringsColorPreviewPanelLayout);
        pyStringsColorPreviewPanelLayout.setHorizontalGroup(
            pyStringsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        pyStringsColorPreviewPanelLayout.setVerticalGroup(
            pyStringsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(pyStringsLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.pyStringsLabel.text")); // NOI18N
        pyStringsLabel.setToolTipText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.pyStringsLabel.toolTipText")); // NOI18N

        pyStringsColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.pyStringsColorTextField.text")); // NOI18N
        pyStringsColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        pyStringsColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(choosePyStringsColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.choosePyStringsColorButton.text")); // NOI18N
        choosePyStringsColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePyStringsColorButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chooseVariablesColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseVariablesColorButton.text")); // NOI18N
        chooseVariablesColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseVariablesColorButtonActionPerformed(evt);
            }
        });

        variablesColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.variablesColorTextField.text")); // NOI18N
        variablesColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        variablesColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(variablesLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.variablesLabel.text")); // NOI18N

        variablesColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        variablesColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        variablesColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout variablesColorPreviewPanelLayout = new javax.swing.GroupLayout(variablesColorPreviewPanel);
        variablesColorPreviewPanel.setLayout(variablesColorPreviewPanelLayout);
        variablesColorPreviewPanelLayout.setHorizontalGroup(
            variablesColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        variablesColorPreviewPanelLayout.setVerticalGroup(
            variablesColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(numbersLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.numbersLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(chooseNumbersColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseNumbersColorButton.text")); // NOI18N
        chooseNumbersColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseNumbersColorButtonActionPerformed(evt);
            }
        });

        numbersColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.numbersColorTextField.text")); // NOI18N
        numbersColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        numbersColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        numbersColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        numbersColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        numbersColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout numbersColorPreviewPanelLayout = new javax.swing.GroupLayout(numbersColorPreviewPanel);
        numbersColorPreviewPanel.setLayout(numbersColorPreviewPanelLayout);
        numbersColorPreviewPanelLayout.setHorizontalGroup(
            numbersColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        numbersColorPreviewPanelLayout.setVerticalGroup(
            numbersColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        featureColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.featureColorTextField.text")); // NOI18N
        featureColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        featureColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(chooseCommentsColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseCommentsColorButton.text")); // NOI18N
        chooseCommentsColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseCommentsColorButtonActionPerformed(evt);
            }
        });

        commentsColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.commentsColorTextField.text")); // NOI18N
        commentsColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        commentsColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(commentsLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.commentsLabel.text")); // NOI18N

        commentsColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        commentsColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        commentsColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout commentsColorPreviewPanelLayout = new javax.swing.GroupLayout(commentsColorPreviewPanel);
        commentsColorPreviewPanel.setLayout(commentsColorPreviewPanelLayout);
        commentsColorPreviewPanelLayout.setHorizontalGroup(
            commentsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        commentsColorPreviewPanelLayout.setVerticalGroup(
            commentsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(chooseStepsColorButton, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.chooseStepsColorButton.text")); // NOI18N
        chooseStepsColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseStepsColorButtonActionPerformed(evt);
            }
        });

        stepsColorTextField.setText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.stepsColorTextField.text")); // NOI18N
        stepsColorTextField.setMinimumSize(new java.awt.Dimension(100, 20));
        stepsColorTextField.setPreferredSize(new java.awt.Dimension(200, 20));

        org.openide.awt.Mnemonics.setLocalizedText(stepsLabel, org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.stepsLabel.text")); // NOI18N
        stepsLabel.setToolTipText(org.openide.util.NbBundle.getMessage(CucumberFeatureOptionsPanel.class, "CucumberFeatureOptionsPanel.stepsLabel.toolTipText")); // NOI18N

        stepsColorPreviewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        stepsColorPreviewPanel.setMaximumSize(new java.awt.Dimension(20, 20));
        stepsColorPreviewPanel.setMinimumSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout stepsColorPreviewPanelLayout = new javax.swing.GroupLayout(stepsColorPreviewPanel);
        stepsColorPreviewPanel.setLayout(stepsColorPreviewPanelLayout);
        stepsColorPreviewPanelLayout.setHorizontalGroup(
            stepsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        stepsColorPreviewPanelLayout.setVerticalGroup(
            stepsColorPreviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(featureColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scenarioColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(examplesColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stringsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pyStringsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(variablesColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numbersColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stepsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scenarioLabel)
                            .addComponent(backgroundLabel)
                            .addComponent(featureLabel)
                            .addComponent(examplesLabel)
                            .addComponent(stringsLabel)
                            .addComponent(pyStringsLabel)
                            .addComponent(variablesLabel)
                            .addComponent(numbersLabel)
                            .addComponent(commentsLabel)
                            .addComponent(stepsLabel))
                        .addGap(4, 4, 4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(featureColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scenarioColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chooseScenarioColorButton)
                            .addComponent(chooseFeatureColorButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(backgroundColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseBackgroundColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(examplesColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseExamplesColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stringsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseStringsColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pyStringsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(choosePyStringsColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(variablesColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseVariablesColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numbersColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseNumbersColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(commentsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseCommentsColorButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stepsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseStepsColorButton)))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chooseFeatureColorButton)
                        .addComponent(featureLabel)
                        .addComponent(featureColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(featureColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chooseScenarioColorButton)
                            .addComponent(scenarioColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scenarioLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scenarioColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chooseBackgroundColorButton)
                        .addComponent(backgroundColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(backgroundLabel))
                    .addComponent(backgroundColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(examplesColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseExamplesColorButton)
                        .addComponent(examplesLabel))
                    .addComponent(examplesColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stringsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseStringsColorButton)
                        .addComponent(stringsLabel))
                    .addComponent(stringsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pyStringsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(choosePyStringsColorButton)
                        .addComponent(pyStringsLabel))
                    .addComponent(pyStringsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(variablesColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseVariablesColorButton)
                        .addComponent(variablesLabel))
                    .addComponent(variablesColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numbersColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseNumbersColorButton)
                        .addComponent(numbersLabel))
                    .addComponent(numbersColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(commentsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseCommentsColorButton)
                        .addComponent(commentsLabel))
                    .addComponent(commentsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stepsColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseStepsColorButton)
                        .addComponent(stepsLabel))
                    .addComponent(stepsColorPreviewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseFeatureColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseFeatureColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Feature", Color.decode(ColorLibrary.getFeatureColor()));
        setChoosenValue(featureColorTextField, featureColorPreviewPanel, color);
    }//GEN-LAST:event_chooseFeatureColorButtonActionPerformed

    private void chooseScenarioColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseScenarioColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Scenario", Color.decode(ColorLibrary.getScenarioColor()));
        setChoosenValue(scenarioColorTextField, scenarioColorPreviewPanel, color);
    }//GEN-LAST:event_chooseScenarioColorButtonActionPerformed

    private void chooseBackgroundColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseBackgroundColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Background", Color.decode(ColorLibrary.getBackgroundColor()));
        setChoosenValue(backgroundColorTextField, backgroundColorPreviewPanel, color);
    }//GEN-LAST:event_chooseBackgroundColorButtonActionPerformed

    private void chooseExamplesColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseExamplesColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Examples", Color.decode(ColorLibrary.getExamplesColor()));
        setChoosenValue(examplesColorTextField, examplesColorPreviewPanel, color);
    }//GEN-LAST:event_chooseExamplesColorButtonActionPerformed

    private void chooseStringsColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseStringsColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Strings", Color.decode(ColorLibrary.getStringsColor()));
        setChoosenValue(stringsColorTextField, stringsColorPreviewPanel, color);
    }//GEN-LAST:event_chooseStringsColorButtonActionPerformed

    private void choosePyStringsColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePyStringsColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Multiline Strings", Color.decode(ColorLibrary.getPyStringsColor()));
        setChoosenValue(pyStringsColorTextField, pyStringsColorPreviewPanel, color);
    }//GEN-LAST:event_choosePyStringsColorButtonActionPerformed

    private void chooseVariablesColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseVariablesColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Variables", Color.decode(ColorLibrary.getVariablesColor()));
        setChoosenValue(variablesColorTextField, variablesColorPreviewPanel, color);
    }//GEN-LAST:event_chooseVariablesColorButtonActionPerformed

    private void chooseNumbersColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseNumbersColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Numbers", Color.decode(ColorLibrary.getNumbersColor()));
        setChoosenValue(numbersColorTextField, numbersColorPreviewPanel, color);
    }//GEN-LAST:event_chooseNumbersColorButtonActionPerformed

    private void chooseCommentsColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseCommentsColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Comments", Color.decode(ColorLibrary.getCommentsColor()));
        setChoosenValue(commentsColorTextField, commentsColorPreviewPanel, color);
    }//GEN-LAST:event_chooseCommentsColorButtonActionPerformed

    private void chooseStepsColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseStepsColorButtonActionPerformed
        Color color = JColorChooser.showDialog(this, "Choose Color for Steps", Color.decode(ColorLibrary.getStepsColor()));
        setChoosenValue(stepsColorTextField, stepsColorPreviewPanel, color);
    }//GEN-LAST:event_chooseStepsColorButtonActionPerformed

    void load() {
        loadPreference(featureColorTextField, featureColorPreviewPanel, ColorLibrary.getFeatureColor());
        loadPreference(scenarioColorTextField, scenarioColorPreviewPanel, ColorLibrary.getScenarioColor());
        loadPreference(backgroundColorTextField, backgroundColorPreviewPanel, ColorLibrary.getBackgroundColor());
        loadPreference(examplesColorTextField, examplesColorPreviewPanel, ColorLibrary.getExamplesColor());
        loadPreference(stringsColorTextField, stringsColorPreviewPanel, ColorLibrary.getStringsColor());
        loadPreference(pyStringsColorTextField, pyStringsColorPreviewPanel, ColorLibrary.getPyStringsColor());
        loadPreference(numbersColorTextField, numbersColorPreviewPanel, ColorLibrary.getNumbersColor());
        loadPreference(variablesColorTextField, variablesColorPreviewPanel, ColorLibrary.getVariablesColor());
        loadPreference(commentsColorTextField, commentsColorPreviewPanel, ColorLibrary.getCommentsColor());
        loadPreference(stepsColorTextField, stepsColorPreviewPanel, ColorLibrary.getStepsColor());
    }

    void store() {
        storePreferences("featureColorPreference", featureColorTextField.getText());
        storePreferences("scenarioColorPreference", scenarioColorTextField.getText());
        storePreferences("backgroundColorPreference", backgroundColorTextField.getText());
        storePreferences("examplesColorPreference", examplesColorTextField.getText());
        storePreferences("stringsColorPreference", stringsColorTextField.getText());
        storePreferences("pyStringsColorPreference", pyStringsColorTextField.getText());
        storePreferences("numbersColorPreference", numbersColorTextField.getText());
        storePreferences("variablesColorPreference", variablesColorTextField.getText());
        storePreferences("commentsColorPreference", commentsColorTextField.getText());
        storePreferences("stepsColorPreference", stepsColorTextField.getText());
    }

    private void setChoosenValue(javax.swing.JFormattedTextField field, javax.swing.JPanel panel, Color color) {
        if(color != null) {
        field.setText("#" + Integer.toHexString(color.getRGB() & 0x00ffffff));
        panel.setBackground(color);
        }
    }

    private void loadPreference(javax.swing.JFormattedTextField field, javax.swing.JPanel panel, String value) {
        field.setText(value);
        panel.setBackground(Color.decode(value));
    }

    private void storePreferences(String key, String value) {
        NbPreferences.forModule(CucumberFeatureOptionsPanel.class).put(key, value);
    }

    boolean valid() {
        return true;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundColorPreviewPanel;
    private javax.swing.JFormattedTextField backgroundColorTextField;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JButton chooseBackgroundColorButton;
    private javax.swing.JButton chooseCommentsColorButton;
    private javax.swing.JButton chooseExamplesColorButton;
    private javax.swing.JButton chooseFeatureColorButton;
    private javax.swing.JButton chooseNumbersColorButton;
    private javax.swing.JButton choosePyStringsColorButton;
    private javax.swing.JButton chooseScenarioColorButton;
    private javax.swing.JButton chooseStepsColorButton;
    private javax.swing.JButton chooseStringsColorButton;
    private javax.swing.JButton chooseVariablesColorButton;
    private javax.swing.JPanel commentsColorPreviewPanel;
    private javax.swing.JFormattedTextField commentsColorTextField;
    private javax.swing.JLabel commentsLabel;
    private javax.swing.JPanel examplesColorPreviewPanel;
    private javax.swing.JFormattedTextField examplesColorTextField;
    private javax.swing.JLabel examplesLabel;
    private javax.swing.JPanel featureColorPreviewPanel;
    private javax.swing.JFormattedTextField featureColorTextField;
    private javax.swing.JLabel featureLabel;
    private javax.swing.JPanel numbersColorPreviewPanel;
    private javax.swing.JFormattedTextField numbersColorTextField;
    private javax.swing.JLabel numbersLabel;
    private javax.swing.JPanel pyStringsColorPreviewPanel;
    private javax.swing.JFormattedTextField pyStringsColorTextField;
    private javax.swing.JLabel pyStringsLabel;
    private javax.swing.JPanel scenarioColorPreviewPanel;
    private javax.swing.JFormattedTextField scenarioColorTextField;
    private javax.swing.JLabel scenarioLabel;
    private javax.swing.JPanel stepsColorPreviewPanel;
    private javax.swing.JFormattedTextField stepsColorTextField;
    private javax.swing.JLabel stepsLabel;
    private javax.swing.JPanel stringsColorPreviewPanel;
    private javax.swing.JFormattedTextField stringsColorTextField;
    private javax.swing.JLabel stringsLabel;
    private javax.swing.JPanel variablesColorPreviewPanel;
    private javax.swing.JFormattedTextField variablesColorTextField;
    private javax.swing.JLabel variablesLabel;
    // End of variables declaration//GEN-END:variables
}
